/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file keyboardlab.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Function prototypes for KeyboardLab.
 *
 ******************************************************************************/

/*
 * KeyboardLab (c) 2021-23 Christopher A. Bohn
 */

#ifndef KEYBOARDLAB_H
#define KEYBOARDLAB_H

char *generate_email(char *destination, size_t destination_size);
int iz_digit(char character);
char decapitalize(char character);
int is_even(int value);
int produce_multiple_of_ten(int seed);

#endif //KEYBOARDLAB_H
