/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file number_builder.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Code to demonstrate "building" a number by polling inputs.
 *
 ******************************************************************************/

/*
 * PollingLab (c) 2021-23 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef NUMBER_BUILDER_H
#define NUMBER_BUILDER_H

#ifdef __cplusplus
extern "C" {
#endif

void initialize_number_system(void);
void build_number(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //NUMBER_BUILDER_H
