/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file common.h
 *
 * @author Christopher A. Bohn
 *
 * @brief A type definition for polling input states,
 *      and fast memory-mapped I/O functions.
 *
 ******************************************************************************/

/*
 * ProximityAlarmLab (c) 2023-25 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef COMMON_H
#define COMMON_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>

typedef enum {
    NOT_PRESSED, RESPOND_TO_PRESS, PRESSED, RESPOND_TO_RELEASE
} input_states_t;

static inline uint32_t get_microseconds(void) { return *(uint32_t volatile *)(0x40054028); }
static inline bool read_pin(uint8_t pin_number) { return !!(*(uint32_t volatile *)(0xD0000004) & (1 << pin_number)); }
static inline void set_pin_high(uint8_t pin_number) { *(uint32_t volatile *)(0xD0000014) = (1 << pin_number); }
static inline void set_pin_low(uint8_t pin_number) { *(uint32_t volatile *)(0xD0000018) = (1 << pin_number); }

#ifdef __cplusplus
} // extern "C"
#endif

#endif //COMMON_H
