/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file sensor.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Code to manage the distance sensor.
 *
 ******************************************************************************/

/*
 * ProximityAlarmLab (c) 2023-25 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef SENSOR_H
#define SENSOR_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>

#define SENSOR_TIMER    (1)
#define ECHO_PIN        (16)
#define TRIGGER_PIN     (17)

typedef enum {
    INITIAL_START, POWERING_UP, READY, ACTIVE_LISTENING, ACTIVE_DETECTED, QUIESCENT
} sensor_states_t;

extern sensor_states_t volatile sensor_state;
extern bool volatile object_detected;
extern unsigned int volatile distance_cm;

void initialize_sensor(void);
void manage_sensor(void);
void initiate_pulse(void);
void process_detection(void);


#ifdef __cplusplus
} // extern "C"
#endif

#endif //SENSOR_H
