/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************/ /**
 *
 * @file sentry.c
 *
 * @author Christopher A. Bohn
 *
 * @brief A proximity alarm that continuously checks for nearby objects,
 *      sounding an alert that becomes more urgent when objects are nearer.
 *      The display shows a visualization of the rangefinder's wavefront
 *      (approximately ±15º from straight ahead) and the corresponding "echo".
 *
 ******************************************************************************/

/*
 * ProximityAlarmLab (c) 2023-26 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "common.h"
#include "alarm.h"
#include "sensor.h"
#include "sentry.h"
#include "display.h"

static uint8_t *backbuffer;

void initialize_sentry(void) {
    backbuffer = get_backbuffer();
}

static void sound_audio_alert(void) {
    static uint32_t last_pulse_at = 0;
    static uint32_t last_chirp_at = 0;
    uint32_t now = get_microseconds();
    if (sensor_state == READY && now - last_pulse_at > 100000U) {
        last_pulse_at = now;
        initiate_pulse();
    }
    process_detection();
    if (object_detected) {
        uint32_t interchirp_time;
        if (distance_cm < 10) {
            interchirp_time = 125000U;
        } else if (distance_cm < 25) {
            interchirp_time = 250000U;
        } else if (distance_cm < 50) {
            interchirp_time = 500000U;
        } else if (distance_cm < 100) {
            interchirp_time = 750000U;
        } else if (distance_cm < 150) {
            interchirp_time = 1000000U;
        } else if (distance_cm < 200) {
            interchirp_time = 1500000U;
        } else if (distance_cm < 250) {
            interchirp_time = 2000000U;
        } else {
            interchirp_time = 2500000U;
        }
        if (now - last_chirp_at > interchirp_time) {
            last_chirp_at = now;
            chirp();
        }
    }
}

static bool is_on_circle(int x, int y, int r) {
    int scaled_distance_squared = 4 * (x * x + y * y);
    int scaled_lower_bound = 4 * r * r - 4 * r + 1; // 4 * (r - 0.5)^2
    int scaled_upper_bound = 4 * r * r + 4 * r + 1; // 4 * (r + 0.5)^2
    return scaled_distance_squared >= scaled_lower_bound
        && scaled_distance_squared <= scaled_upper_bound;
}

// display
#define WIDTH       (128)   // bits
#define HEIGHT       (64)   // bits
#define PANELHEIGHT   (8)   // bits

// arc
#define ORIGIN_COLUMN   (WIDTH / 2)
#define ORIGIN_ROW      (HEIGHT - 1)
#define ASPECT_RATIO    (4)
#define MAXIMUM_RADIUS  (HEIGHT + 2 * ASPECT_RATIO)

// other
#define BITS_PER_BYTE   (8)

static void display_detection(void) {
    static int radius = 0;
    static int counter = 0;
    switch (counter++ % 2) {
        case 0:
            radius = (radius + 1) % MAXIMUM_RADIUS;
            memset(backbuffer, 0, WIDTH * HEIGHT / BITS_PER_BYTE); // clear the previous wavefront
            for (int column = 0; column < WIDTH; column++) {
                int const x = column - ORIGIN_COLUMN;
                for (int row = 0; row < HEIGHT; row++) {
                    int const y = ORIGIN_ROW - row;
                    uint8_t pixel_value = 0;
                    if (abs(x) >= ASPECT_RATIO * (radius - y)) {
                        pixel_value = is_on_circle(x, y, radius);
                    }
                    int distance = (int) distance_cm / 8;
                    if (object_detected) {
                        if (abs(x) >= ASPECT_RATIO * (distance - y)) {
                            pixel_value |= is_on_circle(x, y, distance)
                                || is_on_circle(x, y, distance + 1)
                                || is_on_circle(x, y, distance + 2);
                        }
                    }
                    int panel = row / PANELHEIGHT;
                    uint8_t* display_byte = backbuffer + (panel * WIDTH) + column;
                    int const bit_in_display_byte = row % PANELHEIGHT;
                    *display_byte |= (pixel_value << bit_in_display_byte);
                }
            }
            break;
        case 1:
            refresh_display_no_text();
        default:
            ;
    }
}

void detect_intruders(void) {
    sound_audio_alert();
    display_detection();
}
