/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file sentry.c
 *
 * @author Christopher A. Bohn
 *
 * @brief A proximity alarm that continuously checks for nearby objects,
 *      sounding an alert that becomes more urgent when objects are nearer.
 *
 ******************************************************************************/

/*
 * ProximityAlarmLab (c) 2023-25 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include "common.h"
#include "alarm.h"
#include "sensor.h"
#include "sentry.h"

void detect_intruders(void) {
    static uint32_t last_pulse_at = 0;
    static uint32_t last_chirp_at = 0;
    uint32_t now = get_microseconds();
    if (sensor_state == READY && now - last_pulse_at > 100000U) {
        last_pulse_at = now;
        initiate_pulse();
    }
    process_detection();
    if (object_detected) {
        uint32_t interchirp_time;
        if (distance_cm < 10) {
            interchirp_time = 125000U;
        } else if (distance_cm < 25) {
            interchirp_time = 250000U;
        } else if (distance_cm < 50) {
            interchirp_time = 500000U;
        } else if (distance_cm < 100) {
            interchirp_time = 750000U;
        } else if (distance_cm < 150) {
            interchirp_time = 1000000U;
        } else if (distance_cm < 200) {
            interchirp_time = 1500000U;
        } else if (distance_cm < 250) {
            interchirp_time = 2000000U;
        } else {
            interchirp_time = 2500000U;
        }
        if (now - last_chirp_at > interchirp_time) {
            last_chirp_at = now;
            chirp();
        }
    }
}
