/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file PollingLab.ino
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for PollingLab.
 *
 ******************************************************************************/

/*
 * PollingLab (c) 2021-24 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <CowPi.h>
#include <string.h>
#include "starter.h"
#include "io_functions.h"
#include "number_builder.h"

static bool test_mode;

void setup() {
    initialize_board();
    test_mode = cowpi_left_switch_is_in_right_position();
    initialize_io(cowpi_right_switch_is_in_right_position());
    initialize_number_system();
}

void loop() {
    refresh_display();
    if (test_mode) {
        test_io();
    } else {
        build_number();
    }
}
