/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file listlab.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for ListLab.
 *
 ******************************************************************************/

/*
 * ListLab (c) 2021-26 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include "sorted-test.h"
#include "word-entry-test.h"
#include "list-test.h"

static constexpr size_t NUMBER_OF_TESTS = 7;
extern char const *const LIST_TYPE;

int main(void) {
    fprintf(stderr, "[INFO]  Using %s implementation.\n", LIST_TYPE);
    void (*problem_checkers[NUMBER_OF_TESTS + 1])(void) = {
            nullptr,
            test_word_entry,
            test_list,
            test_alphabetical_functions,
            test_insert_word_empty_list,
            test_insert_word_singleton_list,
            test_insert_word_populated_list,
            test_build_list,
    };
    char *test_names[NUMBER_OF_TESTS + 1] = {
            "Quit",
            "Test word_entry",
            "Test list",
            "Test alphabetical functions",
            "Test insert_word (empty list)",
            "Test insert_word (singleton list)",
            "Test insert_word (populated list)",
            "Create and print book list",
    };
    char buffer[80];
    bool running = true;
    while (running) {
        for (size_t i = 0; i < NUMBER_OF_TESTS + 1; i++) {
            printf("%zu) %s\n", i, test_names[i]);
        }
        printf("Select the task you wish to check: ");
        int scan_count = scanf("%79s", buffer);
        size_t option = (size_t) strtol(buffer, nullptr, 10);
        printf("\n");
        if (option > NUMBER_OF_TESTS) {
            printf("Invalid choice %zu. Please select a choice between 0 and %zu.\n", option, NUMBER_OF_TESTS);
        } else if (option == 0 || scan_count != 1) {
            if (errno == EINVAL || scan_count != 1) {
                printf("Invalid choice (%s). Please select a number between 0 and %zu.\n", buffer, NUMBER_OF_TESTS);
                errno = 0;
            } else {
                printf("Goodbye.\n");
                running = false;
            }
        } else {
            char c;
            if (scanf("%c", &c)) {} // consume the newline character
            problem_checkers[option]();
        }
        printf("\n");
    }
    return 0;
}
