/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file sorted-word-entries.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Functions prototypes for a sorted list of word entries.
 *
 ******************************************************************************/

/*
 * LinkedListLab (c) 2021-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef SORTED_WORD_ENTRIES_H
#define SORTED_WORD_ENTRIES_H

#include <string.h>
#include "list.h"

char *word_to_lowercase(char *destination, const char *word);
bool words_are_equal(const char *word1, const char *word2);
bool word1_is_earlier_than_word2(const char *word1, const char *word2);
bool word1_is_later_than_word2(const char *word1, const char *word2);
list_t *insert_word(list_t *list, char const *word);
list_t *build_list(char const *filename);

#endif //SORTED_WORD_ENTRIES_H
