/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file word-entry-test.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Functions to test the word_entry code.
 *
 ******************************************************************************/

/*
 * LinkedListLab (c) 2021-26 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include "word-entry-test.h"
#include "word-entry.h"

constexpr size_t NUMBER_OF_WORD_ENTRY_FUNCTIONS = 5;

void test_word_entry(void) {
    printf("\nTesting word_entry functions...\n");
    char *function_names[NUMBER_OF_WORD_ENTRY_FUNCTIONS + 1] = {
            "Return to main menu",
            "create_word_entry()",
            "delete_word_entry()",
            "increment_count()",
            "get_count()",
            "get_word()"
    };
    char buffer[80];
    bool running = true;
    word_entry_t *word_entry = nullptr;
    while (running) {
        for (int i = 0; i < NUMBER_OF_WORD_ENTRY_FUNCTIONS + 1; i++) {
            printf("%d) %s\n", i, function_names[i]);
        }
        printf("Select the function you wish to check: ");
        scanf("%79s", buffer);
        errno = 0;
        int option = (int) strtol(buffer, nullptr, 10);
        printf("\n");
        if (option < 0 || option > NUMBER_OF_WORD_ENTRY_FUNCTIONS) {
            printf("Invalid choice %d. Please select a choice between 0 and %zu.\n", option,
                   NUMBER_OF_WORD_ENTRY_FUNCTIONS);
        } else {
            switch (option) {
                case 0:
                    if (errno == EINVAL) {
                        printf("Invalid choice (%s). Please select a number between 0 and %zu.\n", buffer,
                               NUMBER_OF_WORD_ENTRY_FUNCTIONS);
                        errno = 0;
                    } else {
                        printf("Returning to main menu.\n\n");
                        running = false;
                    }
                    break;
                case 1:
                    printf("Creating word_entry. Enter a word: ");
                    scanf("%79s", buffer);
                    word_entry = create_word_entry(buffer);
                    printf("Created --     %s\n", word_entry_to_string(buffer, word_entry));
                    break;
                case 2:
                    printf("Deleting word_entry.\n");
                    if (word_entry == nullptr) {
                        printf("There is no word_entry to delete.\n");
                    } else {
                        delete_word_entry(word_entry);
                        word_entry = nullptr;
                    }
                    break;
                case 3:
                    printf("Incrementing count.\n");
                    if (word_entry == nullptr) {
                        printf("There is no word_entry to increment count.\n");
                    } else {
                        printf("Before increment -- %s\n", word_entry_to_string(buffer, word_entry));
                        increment_count(word_entry);
                        printf("After increment --  %s\n", word_entry_to_string(buffer, word_entry));
                    }
                    break;
                case 4:
                    printf("Getting count: ");
                    if (word_entry == nullptr) {
                        printf("Null Pointer\n");
                    } else {
                        printf("%d\n", get_count(word_entry));
                    }
                    break;
                case 5:
                    printf("Getting word: ");
                    if (word_entry == nullptr) {
                        printf("Null Pointer\n");
                    } else {
                        char const *word = get_word(word_entry);
                        printf("%s\n", word ? word : "get_word() returned nullptr.");
                    }
                    break;
                default:
                    // include this here in case we change NUMBER_OF_WORD_ENTRY_FUNCTIONS without adding all the required cases
                    fprintf(stderr, "Reached unreachable code with option value %d (file %s, line %d in function %s).\n", option, __FILE__, __LINE__, __func__);
                    unreachable();
            }
        }
        printf("\n");
    }
}
