/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file calculatorlab.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for ControlPanelLab.
 *
 ******************************************************************************/

/*
 * CalculatorLab (c) 2020-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <CowPi.h>
#include "display.h"
#include "seven_segment_rom.h"
#include "seven_segment_pla.h"
#include "number_builder.h"
#include "calculator.h"

static void demonstrate_kmap(void);
static void demonstrate_polling(void);

static enum {DEMONSTRATE_LOGIC_DESIGN, DEMONSTRATE_POLLING, CALCULATOR} mode;

void setup(void) {
    cowpi_setup(0,
                (cowpi_display_module_t) {
                        .display_module = SEVEN_SEGMENT
                },
                (cowpi_display_module_protocol_t) {
                        .protocol = COWPI_SPI,
                        .data_pin = 19,
                        .clock_pin = 18,
                        .select_pin = 17
                }
               );
    initialize_display(16);
    draw_logo();
    delay(1000);
    clear_display();
    if (cowpi_right_switch_is_in_left_position()) {
        if (cowpi_left_switch_is_in_left_position()) {
            mode = DEMONSTRATE_LOGIC_DESIGN;
            display_string(7, "logic design");
        } else {
            display_string(7, "polling");
            mode = DEMONSTRATE_POLLING;
        }
    } else {
        display_string(7, "calculator");
        mode = CALCULATOR;
    }
}

void loop(void) {
    switch (mode) {
        case DEMONSTRATE_LOGIC_DESIGN:
            demonstrate_kmap();
            break;
        case DEMONSTRATE_POLLING:
            demonstrate_polling();
            break;
        case CALCULATOR:
            calculate();
            break;
        default:
            display_string(0, "****************");
            display_string(1, "Unexpected Mode!");
            display_string(2, "****************");
    }
    count_visits(7);
}

static void demonstrate_kmap(void) {
    static int i = 0;
    uint32_t start;
    digitalWrite(17, 0);
    cowpi_spi_transmit(1);
    cowpi_spi_transmit(bcd_to_7segment_rom(i));
    digitalWrite(17, 1);
    start = get_microseconds();
    while (get_microseconds() - start < 1000) {}
    digitalWrite(17, 0);
    cowpi_spi_transmit(2);
    cowpi_spi_transmit(bcd_to_7segment_pla(i));
    digitalWrite(17, 1);
    start = get_microseconds();
    while (get_microseconds() - start < 1000000) {}
    i = (i + 1) % 10;
}

static void demonstrate_polling() {
    static char buffer[17];
    build_number();
    sprintf(buffer, "%6d %8s", get_number(), number_overflowed() ? "overflow" : "");
    display_string(0, buffer);
}
