/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file number_builder.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Code to demonstrate "building" a number by polling inputs.
 *
 ******************************************************************************/

/*
 * CalculatorLab (c) 2020-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef NUMBER_BUILDER_H
#define NUMBER_BUILDER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

static inline uint32_t get_microseconds(void) { return micros(); }

int16_t get_number(void);
bool number_overflowed(void);
void reset_number(void);
void build_number(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //NUMBER_BUILDER_H