/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file seven_segment_rom.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Code to simulate a seven-segment decoder implemented with a ROM.
 *
 ******************************************************************************/

/*
 * CalculatorLab (c) 2020-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef SEVEN_SEGMENT_ROM_H
#define SEVEN_SEGMENT_ROM_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

uint8_t bcd_to_7segment_rom(uint8_t digit);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //SEVEN_SEGMENT_ROM_H
