/*                       *
* DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file basetwo.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Function prototypes, macros, and type declarations for IntegerLab.
 *
 ******************************************************************************/

/*
 * IntegerLab (c) 2018-26 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef BASETWO_H
#define BASETWO_H

#include <assert.h>
#include <stdint.h>
#if __has_include(<stdbit.h>)
    #include <stdbit.h>
#else
    #define stdc_count_ones(number) __builtin_popcount(number)
#endif

/*
 * PREDEFINED MACROS THAT DO NOT DEPEND ON STUDENT CODE
 */

#define is_zero(number)         (!(number))
#define is_not_zero(number)     (!!(number))
#define is_power_of_two(number) (stdc_count_ones(number) == 1)
#define LOWER_BITS_MASK(n)      ((UINT64_C(1) << (n)) - UINT64_C(1))

/*
 * UTILITY FUNCTIONS
 */

uint32_t exponentiate(unsigned int exponent);
unsigned int lg(uint32_t power_of_two);

#endif //BASETWO_H
