/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file ieee754-to-string.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Auxiliary functions for FloatLab.
 *
 ******************************************************************************/

/*
 * FloatLab (c) 2019-26 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <assert.h>
#include <stdio.h>
#include "ieee754-to-string.h"
#include "fpu.h"
#include "constants.h"

static char *bits_to_string(char *destination, uint64_t bits, int start_bit,
                            int end_bit, enum bit_divider_direction bit_dividers) {
    assert(start_bit < 64 && start_bit >= 0 && end_bit < 64 && end_bit >= 0);
    if (start_bit < end_bit) {
        int placeholder = start_bit;
        start_bit = end_bit;
        end_bit = placeholder;
    }
    uint64_t mask = (uint64_t) 1 << start_bit;
    char *destination_bit = destination;
    int place_counter = (bit_dividers == FROM_LEFT) ? 0 : (end_bit - start_bit - 1) % 4;
    for (int bit = start_bit; bit >= end_bit; bit--) {
        *destination_bit++ = (bits & mask) ? '1' : '0';
        mask = mask >> 1;
        place_counter = (place_counter + 1) % 4;
        if (!place_counter && (bit_dividers != NONE)) {
            *destination_bit++ = '\'';
        }
    }
    if (*(destination_bit - 1) == '\'') {
        destination_bit--;
    }
    *destination_bit = '\0';
    return destination;
}

/**
 * @brief Converts an IEEE 754-compliant number to a string depicting the
 * number's value as a base-2 floating point number.
 *
 * Unless the number is infinity, NaN, or zero, the expected string consists of
 * the sign (+ or -), then single bit, then a binary point, then the fractional
 * bits, followed by "_{2} x 2^{exponent}" where the exponent is expressed in
 * decimal.
 *
 * The caller is responsible for providing a buffer of sufficient size to hold
 * the string (57 bytes is sufficient).
 *
 * @param destination a buffer to hold the string
 * @param number the value to be converted into a string
 * @return the destination buffer containing the number's string representation
 */
char *ieee754_to_string(char *destination, ieee754_t number) {
    sprintf(destination, "%#010x\t", number);
    sprintf(destination + 11, "%c", is_negative(number) ? '-' : '+');
    if (is_nan(number)) {
        sprintf(destination + 12, "Not a Number");
    } else if (is_infinity(number)) {
        sprintf(destination + 12, "Infinity");
    } else if (is_zero(number)) {
        sprintf(destination + 12, "0.0");
    } else {
        // The number is either Normal or Subnormal
        uint8_t integer = get_754_integer(number);
        uint32_t fraction = get_754_fraction(number);
        int8_t exponent = get_754_exponent(number);
        char fraction_string[40];
        sprintf(destination + 12, "%u.%s_{2} x 2^{%d}",
                integer,
                bits_to_string(fraction_string, fraction, NUMBER_OF_FRACTION_BITS - 1, 0, FROM_LEFT),
                exponent);
    }
    return destination;
}
