/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file bits-to-string.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Auxiliary function prototype and type declaration for FloatLab.
 *
 ******************************************************************************/

/*
 * FloatLab (c) 2019-26 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef BITS_TO_STRING_H
#define BITS_TO_STRING_H

#include "fpu.h"

enum bit_divider_direction {
    NONE, FROM_LEFT, FROM_RIGHT
};

char *ieee754_to_string(char *destination, ieee754_t number);

#endif //BITS_TO_STRING_H
