/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/*
 * PointerLab (c) 2021-22 Christopher A. Bohn
 */

/******************************************************************************
 * This header provides the node data structure for a linked list; and it
 * provides the function prototypes.
 ******************************************************************************/

#ifndef CHALLENGE_RESPONSE_H
#define CHALLENGE_RESPONSE_H

#define MAXIMUM_WORD_LENGTH 60

struct node {
    char word[MAXIMUM_WORD_LENGTH];
    int occurrences;
    struct node *next;
    struct node *previous;
};

char decapitalize(char character);      // linked from problem2.c
int is_even(int value);                 // linked from problem3.c
struct node *create_node(const char *word);
void insert_after(struct node *existing_node, struct node *new_node);
void insert_before(struct node *existing_node, struct node *new_node);
char *word_to_lowercase(const char *word);
int compare_words(const char *word1, const char *word2);
struct node *insert_word(struct node *head, const char *word);
struct node *build_list(const char *filename);
char *respond(const struct node *list, const char *challenge_word);
char *get_input(const char *prompt);

#endif //CHALLENGE_RESPONSE_H
