/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file calculator.h
 *
 * @author Christopher A. Bohn
 *
 * @brief A four-function calculator that uses other, student-written code.
 *
 ******************************************************************************/

/*
 * CalculatorLab (c) 2020-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef CALCULATOR_H
#define CALCULATOR_H

#ifdef __cplusplus
extern "C" {
#endif

void calculate(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //CALCULATOR_H
