/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file seven_segment_rom.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Code to simulate a seven-segment decoder implemented with a ROM.
 *
 ******************************************************************************/

/*
 * CalculatorLab (c) 2020-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <stdbool.h>
#include "seven_segment_rom.h"

enum {
    A_SEGMENT = 0,
    B_SEGMENT,
    C_SEGMENT,
    D_SEGMENT,
    E_SEGMENT,
    F_SEGMENT,
    G_SEGMENT
};

static bool rom[16][8] = {
        /*       A  B  C  D  E  F  G  UNUSED    */
        /* 0 */ {1, 1, 1, 1, 1, 1, 0, 0},
        /* 1 */ {0, 1, 1, 0, 0, 0, 0, 0},
        /* 2 */ {1, 1, 0, 1, 1, 0, 1, 0},
        /* 3 */ {1, 1, 1, 1, 0, 0, 1, 0},
        /* 4 */ {0, 1, 1, 0, 0, 1, 1, 0},
        /* 5 */ {1, 0, 1, 1, 0, 1, 1, 0},
        /* 6 */ {1, 0, 1, 1, 1, 1, 1, 0},
        /* 7 */ {1, 1, 1, 0, 0, 0, 0, 0},
        /* 8 */ {1, 1, 1, 1, 1, 1, 1, 0},
        /* 9 */ {1, 1, 1, 1, 0, 1, 1, 0},
        /* non-decimal combinations follow */
        /* A */ {0, 0, 0, 0, 0, 0, 0, 0},
        /* B */ {0, 0, 0, 0, 0, 0, 0, 0},
        /* C */ {0, 0, 0, 0, 0, 0, 0, 0},
        /* D */ {0, 0, 0, 0, 0, 0, 0, 0},
        /* E */ {0, 0, 0, 0, 0, 0, 0, 0},
        /* F */ {0, 0, 0, 0, 0, 0, 0, 0}
};


uint8_t bcd_to_7segment_rom(uint8_t digit) {
    return rom[digit][A_SEGMENT] << 6 |
           rom[digit][B_SEGMENT] << 5 |
           rom[digit][C_SEGMENT] << 4 |
           rom[digit][D_SEGMENT] << 3 |
           rom[digit][E_SEGMENT] << 2 |
           rom[digit][F_SEGMENT] << 1 |
           rom[digit][G_SEGMENT] << 0 ;
}
