/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file cart_controller.h
 *
 * @author Christopher A. Bohn
 *
 * @brief An initialization function and main loop function for the
 *    simulated control of a simulated cart.
 *
 ******************************************************************************/

/*
 * InterruptLab (c) 2021-23 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef CART_CONTROLLER_H
#define CART_CONTROLLER_H

#ifdef __cplusplus
extern "C" {
#endif

void initialize_cart_system(void);
void control_cart(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //CART_CONTROLLER_H
