/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file turn_signals.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Definitions for the state machine reprsenting the turn signal
 *    subsystem of a remote-controlled cart.
 *
 ******************************************************************************/

/*
 * InterruptLab (c) 2021-23 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef TURN_SIGNALS_H
#define TURN_SIGNALS_H

#ifdef __cplusplus
extern "C" {
#endif

enum turn_directions {
  NO_TURN,
  LEFT_TURN,
  RIGHT_TURN
};

extern volatile enum turn_directions indicated_turn_direction;

void initialize_turn_signals(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //TURN_SIGNALS_H
