/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file challenge-response-test.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Functions to test the "challenge/response" application.
 *
 ******************************************************************************/

/*
 * LinkedListLab (c) 2021-24 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <stdlib.h>
#include <stdio.h>
#include "challenge-response-test.h"
#include "challenge-response.h"

static char *get_input(char *destination, const char *prompt) {
    printf("%s: ", prompt);
    fgets(destination, MAXIMUM_WORD_LENGTH, stdin);
    destination[strlen(destination) - 1] = '\0';    // eliminates the undesired newline character
    return destination;
}

void test_alphabetical_functions(void) {
    char word[MAXIMUM_WORD_LENGTH + 1];
    char word1[MAXIMUM_WORD_LENGTH + 1];
    get_input(word, "Enter the first word");
    word_to_lowercase(word1, word);
    printf("word_to_lowercase(%s) = %s\n", word, word1);
    char word2[MAXIMUM_WORD_LENGTH + 1];
    get_input(word, "Enter the second word");
    word_to_lowercase(word2, word);
    printf("word_to_lowercase(%s) = %s\n", word, word2);
    printf("words_are_equal(%s, %s) = %s\n",
           word1, word2, words_are_equal(word1, word2) ? "true" : "false");
    printf("word1_is_earlier_than_word2(%s, %s) = %s\n",
           word1, word2, word1_is_earlier_than_word2(word1, word2) ? "true" : "false");
    printf("word1_is_later_than_word2(%s, %s) = %s\n",
           word1, word2, word1_is_later_than_word2(word1, word2) ? "true" : "false");
}

void test_insert_word_empty_list(void) {
    printf("Creating an empty list for the test.\n");
    list_t *list = create_list();
    print(list);
    printf("\n");
    char word[MAXIMUM_WORD_LENGTH + 1];
    get_input(word, "Enter the word to be inserted into the list");
    list = insert_word(list, word);
    printf("\n");
    print(list);
    destroy_list(list, true);
}

void test_insert_word_populated_list(void) {
    printf("Creating and populating a list for the test.\n");
    // I'm going to break encapsulation for the benefit of the test...
    word_entry_t word_entries[] = {
            {.word="bar", .occurrences=2},
            {.word="baz", .occurrences=3},
            {.word="foo", .occurrences=1},
            {.word="plugh", .occurrences=6},
            {.word="quux", .occurrences=5},
            {.word="xyzzy", .occurrences=4}
    };
    list_t *list = create_list();
    for (size_t i = 0; i < sizeof(word_entries) / sizeof(word_entry_t); i++) {  // this works because the size of the array is known at compile-time
        list = append(list, word_entries + i);
    }
    print(list);
    printf("\n");
    char word[MAXIMUM_WORD_LENGTH + 1];
    get_input(word, "Enter the word to be inserted into the list");
    list = insert_word(list, word);
    printf("\n");
    print(list);
    word_entry_t *word_entry = get_word_entry(list);
    destroy_list(list, false);  // most of the word entries were created on the stack, not malloc'd
    char lowercase_word[MAXIMUM_WORD_LENGTH + 1];
    word_to_lowercase(lowercase_word, word);
    if (strcmp(lowercase_word, "bar")   && strcmp(lowercase_word, "baz")  && strcmp(lowercase_word, "foo") &&
        strcmp(lowercase_word, "plugh") && strcmp(lowercase_word, "quux") && strcmp(lowercase_word, "xyzzy")) {
        // the word isn't any of the original words
        free(word_entry);
    }
}

void test_build_list(void) {
    char input[MAXIMUM_WORD_LENGTH + 1];
    get_input(input, "Enter the name of the book file");
    printf("Building the list.\n");
    list_t *list = build_list(input);
    print(list);
    delete(list, true);
}

void test_challenge_response(void) {
    char input[MAXIMUM_WORD_LENGTH + 1];
    char lowercase_input[MAXIMUM_WORD_LENGTH + 1];
    char output[MAXIMUM_WORD_LENGTH + 1];
    get_input(input, "Enter the name of the book file");
    printf("Building the list.\n");
    list_t *list = build_list(input);
    do {
        get_input(input, "Enter the challenge word (or blank input to return to main menu)");
        if (input[0]) {     // if there was a non-blank input
            word_to_lowercase(lowercase_input, input);
            printf("Challenge word: %s\n", lowercase_input);
            printf("Response word:  %s\n", respond(list, output, lowercase_input));
        }
    } while (input[0]);
    delete(list, true);
}
