/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file data-structure-test.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Functions prototypes for testing the data structures used by the
 *      "challenge/response" application.
 *
 ******************************************************************************/

/*
 * LinkedListLab (c) 2021-24 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef WORD_ENTRY_TEST_H
#define WORD_ENTRY_TEST_H

void test_word_entry(void);
void test_list(void);

#endif //WORD_ENTRY_TEST_H
