/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file list-test.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Function prototypes for testing the list code (should work with both
 *      arraylist and linkedlist).
 *
 ******************************************************************************/

/*
 * LinkedListLab (c) 2021-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef LIST_TEST_H
#define LIST_TEST_H

void test_list(void);

#endif //LIST_TEST_H
