/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file sorted-test.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Functions prototypes for testing the "challenge/response" application.
 *
 ******************************************************************************/

/*
 * LinkedListLab (c) 2021-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef SORTED_TEST_H
#define SORTED_TEST_H

void test_alphabetical_functions(void);
void test_insert_word_empty_list(void);
void test_insert_word_singleton_list(void);
void test_insert_word_populated_list(void);
void test_build_list(void);

#endif //SORTED_TEST_H
