/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file word_entry.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Structure definition and function prototypes for word entries to be
 *      used in lists for the "challenge/response" application.
 *
 ******************************************************************************/

/*
 * LinkedListLab (c) 2021-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef WORD_ENTRY_H
#define WORD_ENTRY_H

#define MAXIMUM_WORD_LENGTH (50)

typedef struct {
    char word[MAXIMUM_WORD_LENGTH + 1];
    int occurrences;
} word_entry_t;

word_entry_t *create_word_entry(char const *word);
void delete_word_entry(word_entry_t *word_entry);
void increment_count(word_entry_t *word_entry);
int get_count(word_entry_t const *word_entry);
char const *get_word(word_entry_t const *word_entry);
char *word_entry_to_string(char *destination, word_entry_t const *word_entry);


#endif //WORD_ENTRY_H
