#                       #
# DO NOT EDIT THIS FILE #
#                       #

###############################################################################
#
# @file authoritative_x86_64_macos.asm
#
# @author Christopher A. Bohn
#
# @brief Implementation of arithmetic authoritative results, written in x86_64
#       assembly for MacOS
#
# The code within the functions was hand-written (and is common to all x86_64
#       Unix-like systems); however, the surrounding directives were prepared
#       by a compiler.
#
###############################################################################

#
# IntegerLab (c) 2018-23 Christopher A. Bohn
#
# Starter code licensed under the Apache License, Version 2.0
# (http://www.apache.org/licenses/LICENSE-2.0).
#

#include "authoritative_results.h"

#if defined X86_64_MACOS

	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 12, 0	sdk_version 13, 1
	.globl	_evaluate_addition              ## -- Begin function evaluate_addition
	.p2align	4, 0x90
_evaluate_addition:                     ## @evaluate_addition
	.cfi_startproc
## %bb.0:
    addw %si, %di
    setz 4(%rdx)
    sets 5(%rdx)
    seto 6(%rdx)
    setc 7(%rdx)
    movw %di, (%rdx)
    retq
	.cfi_endproc
                                        ## -- End function
	.globl	_evaluate_subtraction           ## -- Begin function evaluate_subtraction
	.p2align	4, 0x90
_evaluate_subtraction:                  ## @evaluate_subtraction
	.cfi_startproc
## %bb.0:
    subw %si, %di
    setz 4(%rdx)
    sets 5(%rdx)
    seto 6(%rdx)
    setc 7(%rdx)
    movw %di, (%rdx)
	retq
	.cfi_endproc
                                        ## -- End function
	.globl	_evaluate_unsigned_multiplication ## -- Begin function evaluate_unsigned_multiplication
	.p2align	4, 0x90
_evaluate_unsigned_multiplication:      ## @evaluate_unsigned_multiplication
	.cfi_startproc
## %bb.0:
	pushq %rax
	pushq %rdx
	movw %di, %ax
	mulw %si
	movw %dx, %di
	popq %rdx
	setz 4(%rdx)
	sets 5(%rdx)
	seto 6(%rdx)
	setc 7(%rdx)
	movw %ax, (%rdx)
	movw %di, 2(%rdx)
	popq %rax
	retq
	.cfi_endproc
                                        ## -- End function
	.globl	_evaluate_unsigned_division     ## -- Begin function evaluate_unsigned_division
	.p2align	4, 0x90
_evaluate_unsigned_division:            ## @evaluate_unsigned_division
	.cfi_startproc
## %bb.0:
	pushq %rax
	pushq %rdx
	movw %di, %ax
	movw $0, %dx
	divw %si
	movw %dx, %di
	popq %rdx
	setz 4(%rdx)
	sets 5(%rdx)
	seto 6(%rdx)
	setc 7(%rdx)
	movw %ax, (%rdx)
	movw %di, 2(%rdx)
	popq %rax
	retq
	.cfi_endproc
                                        ## -- End function
	.globl	_evaluate_signed_multiplication ## -- Begin function evaluate_signed_multiplication
	.p2align	4, 0x90
_evaluate_signed_multiplication:        ## @evaluate_signed_multiplication
	.cfi_startproc
## %bb.0:
	pushq %rax
	pushq %rdx
	movw %di, %ax
	imulw %si
	movw %dx, %di
	popq %rdx
	setz 4(%rdx)
	sets 5(%rdx)
	seto 6(%rdx)
	setc 7(%rdx)
	movw %ax, (%rdx)
	movw %di, 2(%rdx)
	popq %rax
	retq
	.cfi_endproc
                                        ## -- End function
	.globl	_evaluate_signed_division       ## -- Begin function evaluate_signed_division
	.p2align	4, 0x90
_evaluate_signed_division:              ## @evaluate_signed_division
	.cfi_startproc
## %bb.0:
	pushq %rax
	pushq %rdx
	movw %di, %ax
	movw $0, %dx
	testw %ax, %ax
	# cmovs $-1, %rdx
	# the next two instructions substitute for the cmov instruction, which cannot move from immediate to register
	jns .Lcmovsubstitute
	movw $-1, %dx
.Lcmovsubstitute:
	# the previous two instructions substitute for the cmov instruction
	idivw %si
	movw %dx, %di
	popq %rdx
	setz 4(%rdx)
	sets 5(%rdx)
	seto 6(%rdx)
	setc 7(%rdx)
	movw %ax, (%rdx)
	movw %di, 2(%rdx)
	popq %rax
	retq
	.cfi_endproc
                                        ## -- End function
.subsections_via_symbols

#endif