/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file profiler.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Function prototypes for public code that profiles IntegerLab.
 *
 ******************************************************************************/

/*
 * IntegerLab (c) 2018-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef PROFILER_H
#define PROFILER_H

#include "alu.h"

[[gnu:no_instrument_function]] void reset_call_counts(void);
[[gnu:no_instrument_function]] int get_call_counts(const void *);

#endif //PROFILER_H
