/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file InterruptLab.ino
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for InterruptLab.
 *
 ******************************************************************************/

/*
 * InterruptLab (c) 2021-23 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <CowPi.h>
#include "i2c_address.h"
#include "cart_controller.h"
#include "turn_signals.h"

void setup() {
  cowpi_stdio_setup(9600);
  cowpi_set_display_i2c_address(I2C_ADDRESS);
  cowpi_setup(LCD1602 | I2C);
  cowpi_lcd1602_set_backlight(true);
  initialize_turn_signals();
  initialize_cart_system();
}

void loop() {
  control_cart();
}
