/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file card.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Card-related type definitions, constants, and function prototypes for
 *      PokerLab.
 *
 ******************************************************************************/

/*
 * PokerLab Assignment and starter code (c) 2018-26 Christopher A. Bohn
 */

#ifndef CARD_H
#define CARD_H

typedef enum {
    CLUBS = 0,
    DIAMONDS,
    HEARTS,
    SPADES,
    NUMBER_OF_SUITS
} suit_t;

typedef struct {
    int value;      // 1=Ace, 11=Jack, 12=Queen, 13=King. 2-10 as that number. No other values allowed.
    suit_t suit;
} card_t;

static char *const suit_to_string[] = {"CLUBS", "DIAMONDS", "HEARTS", "SPADES"};
constexpr int MINIMUM_NUMBER_VALUE  = 2;
constexpr int MAXIMUM_NUMBER_VALUE  = 10;
enum face_cards {
    ACE = 1,
    JACK = 11,
    QUEEN,
    KING
};
constexpr int MINIMUM_VALUE         = ACE;
constexpr int MAXIMUM_VALUE         = KING;
constexpr int SIZE_OF_DECK          = NUMBER_OF_SUITS * (MAXIMUM_NUMBER_VALUE - MINIMUM_VALUE + 1);

card_t *create_card(int value, suit_t suit, card_t *destination);
char *card_to_string(const card_t *card, char *destination);

#endif  //CARD_H
