/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file poker.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Deck- and hand-related function prototypes for PokerLab.
 *
 ******************************************************************************/

/*
 * PokerLab Assignment and starter code (c) 2018-26 Christopher A. Bohn
 */

#ifndef POKER_H
#define POKER_H

card_t *get_random_hand(card_t *destination, int size_of_hand);
card_t *get_specific_hand(card_t *destination, int const *indices, int size_of_hand);
void print_deck(void);
void characterize_hand(card_t const *hand, int size_of_hand);

#endif //POKER_H
