/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file word-entry-test.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Function prototypes for testing the word_entry code.
 *
 ******************************************************************************/

/*
 * LinkedListLab (c) 2021-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef WORD_ENTRY_TEST_H
#define WORD_ENTRY_TEST_H

void test_word_entry(void);

#endif //WORD_ENTRY_TEST_H
