/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file io_functions.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Code to read inputs and write to outputs.
 *
 ******************************************************************************/

/*
 * RotaryMotionLab (c) 2025 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef IO_FUNCTIONS_H
#define IO_FUNCTIONS_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define A_WIPER_PIN         (17)
#define B_WIPER_PIN         (A_WIPER_PIN - 1)
#define SERVO_PIN           (22)

void initialize_io(void);
uint32_t get_quadrature(void);
void set_servo_pin(bool logic_value);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //IO_FUNCTIONS_H