/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file rotary-encoder.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Function prototypes and a type definition to report the direction that
 *      the rotary encoder is turning or has turned.
 *
 ******************************************************************************/

/*
 * RotaryMotionLab (c) 2025 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef ROTARY_ENCODER_H
#define ROTARY_ENCODER_H

typedef enum {
    STATIONARY = 0, CLOCKWISE, COUNTERCLOCKWISE
} direction_t;

void sample_rotary_encoder(void);
direction_t get_direction(void);
void count_rotations(void);

#endif //ROTARY_ENCODER_H