/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file timer.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Code to generate a periodic timer interrupt that is used to shape a
 *      servo's pulse and to sample a rotary encoder.
 *
 ******************************************************************************/

/*
 * RotaryMotionLab (c) 2025 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef TIMER_H
#define TIMER_H

void initialize_timer(void);

#endif //TIMER_H
