/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file PollingLab.cpp
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for PollingLab.
 *
 ******************************************************************************/

/*
 * PollingLab (c) 2021-24 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <CowPi.h>
#include "display.h"
#include "io_functions.h"
#include "number_builder.h"

static bool test_mode;

void setup() {
    record_build_timestamp(__FILE__, __DATE__, __TIME__);
    cowpi_setup(0,
                (cowpi_display_module_t) {.display_module = NO_MODULE},
                (cowpi_display_module_protocol_t) {.protocol = NO_PROTOCOL}
               );
    initialize_display(21);
//    initialize_display(16);

    test_mode = cowpi_left_switch_is_in_right_position();
    initialize_io(cowpi_right_switch_is_in_right_position());
    initialize_number_system();

    print_build_timestamps(true);
}

void loop() {
    refresh_display();
    if (test_mode) {
        test_io();
    } else {
        build_number();
    }
    count_visits(7);
}
