/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file duplicatorlab.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Function prototypes and type declarations for DuplicatorLab.
 *
 ******************************************************************************/

/*
 * DuplicatorLab (c) 2022 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef DUPLICATOR_H
#define DUPLICATOR_H

#define BUFFER_SIZE 120

void *read_original(void *arg);
void *write_copy(void *arg);
void duplicate(FILE *source_file, FILE *destination_file);

#endif //DUPLICATOR_H
