/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file duplicatorlab.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for DuplicatorLab.
 *
 ******************************************************************************/

/*
 * DuplicatorLab (c) 2022 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <stdio.h>
#include <stdlib.h>
#include "duplicator.h"

int main(int argv, const char *argc[]) {
    if (argv != 3) {
        fprintf(stderr, "Usage: duplicator <sourcefile> <destinationfile>\n");
        exit(1);
    }
    FILE *source_file = fopen(argc[1], "r");
    if (!source_file) {
        fprintf(stderr, "Error! File %s does not exist.\n", argc[1]);
        exit(1);
    }
    FILE *destination_file = fopen(argc[2], "w");
    duplicate(source_file, destination_file);
    fclose(source_file);
    fclose(destination_file);
}
