/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file control_panel.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for ControlPanelLab.
 *
 ******************************************************************************/

/*
 * ControlPanelLab (c) 2021-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <CowPi.h>
#include "display.h"
#include "io_functions.h"

FILE *seven_segment;

void setup() {
    seven_segment = cowpi_setup(0,
            (cowpi_display_module_t) {
                    .display_module = SEVEN_SEGMENT
            },
            (cowpi_display_module_protocol_t) {
                    .protocol = COWPI_SPI,
                    .data_pin = 19,
                    .clock_pin = 18,
                    .select_pin = 17
            }
    );
    initialize_display(16);
    draw_logo();
    delay(1000);
    clear_display();
    initialize_io(cowpi_right_switch_is_in_right_position());
    fprintf(seven_segment, "foo\n");
}

void loop() {
    test_io();
    count_visits(7);
}
