/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file keyboardlab.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for KeyboardLab.
 *
 ******************************************************************************/

/*
 * KeyboardLab (c) 2021-26 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <ctype.h>
#include <errno.h>
#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "keyboardlab.h"

#define NUMBER_OF_PROBLEMS 3

void print_five_characters(const char *string, int central_position) {
    bool past_terminator = false;
    for (int i = central_position - 2; i <= central_position + 2; i++) {
        if (i < 0 || past_terminator) {
            printf(" ");
        } else {
            if (!string[i]) {
                printf("\\0");
                past_terminator = true;
            } else if (string[i] == '\\') {
                printf("\\\\");
            } else if (isprint(string[i])) {
                printf("%c", string[i]);
            } else if (string[i] == '\a') {
                printf("\\a");
            } else if (string[i] == '\b') {
                printf("\\b");
            } else if (string[i] == '\t') {
                printf("\\t");
            } else if (string[i] == '\n') {
                printf("\\n");
            } else if (string[i] == '\v') {
                printf("\\v");
            } else if (string[i] == '\f') {
                printf("\\f");
            } else if (string[i] == '\r') {
                printf("\\r");
            } else {
                printf("\\.");
            }
        }
    }
    printf("\n");
}

int produce_multiple_of_ten_reference(int seed) {
    int value = seed > 0 ? seed : 0;
    int position_of_last_digit = value > 0 ? (int) log10(value) : 0;
    char value_text[33];
    sprintf(value_text, "%d", value);
    while (value_text[position_of_last_digit] != '0') {
        if (value % 2 == 0) {
            value = value / 2;
        } else {
            int difference = value - 1;
            int five = 5;
            value = difference * five;
        }
        position_of_last_digit = value > 0 ? (int) log10(value) : 0;
        sprintf(value_text, "%d", value);
    }
    return value;
}

void check_problem1(void) {
    char const desired_message[] =
            {
#embed "../data/problem1oracle.txt"
            , '\0'
            };
    int const buffer_length = 3 * sizeof(desired_message);
    // pre-fill the buffer with `\0`s so students don't need to worry about that
    char *buffer = calloc(buffer_length, sizeof(char));
    buffer = generate_email(buffer, buffer_length);
    char *terminator = strchr(buffer, '\0');                    // strchr will eventually find a NUL character
    if (terminator - buffer >= buffer_length) {                 // does the NUL appear within the buffer?
        printf("*** Your string (%ld characters) is much too long! ***", strlen(buffer));
    } else {
        printf("%s\n", buffer);
        if (!strcmp(desired_message, buffer)) {
            printf("*** Your string matches the desired message. ***\n");
        } else {
            printf("*** Your string differs from the desired message. ***\n");
            int i = 0;
            while (buffer[i] == desired_message[i]) {
                i++;
            }
            printf("The strings differ at character %d\n", i);
            printf("                   ");
            int extra_spaces_needed =
                    ((isprint(buffer[i - 2]) || i < 2) ? 0 : 1) + ((isprint(buffer[i - 1]) || i < 1) ? 0 : 1);
            while (extra_spaces_needed) {
                printf(" ");
                extra_spaces_needed--;
            }
            printf("v (ASCII 0x%02X)\n", buffer[i]);
            printf("Your string:     ");
            print_five_characters(buffer, i);
            printf("Desired message: ");
            print_five_characters(desired_message, i);
            printf("                   ");
            extra_spaces_needed =
                    ((isprint(buffer[i - 2]) || i < 2) ? 0 : 1) + ((isprint(buffer[i - 1]) || i < 1) ? 0 : 1);
            while (extra_spaces_needed) {
                printf(" ");
                extra_spaces_needed--;
            }
            printf("^ (ASCII 0x%02X)\n", desired_message[i]);
        }
    }
    free(buffer);
}

void check_problem2(void) {
    printf("Enter character: ");
    char c;
    while ((c = (char) getchar()) == '\n') {}
    printf("Reference:\tisdigit('%c') =  %d\t\ttolower('%c') =      %c\n", c, !!isdigit(c), c, tolower(c));
    printf("Your code:\tiz_digit('%c') = %d\t\tdecapitalize('%c') = %c\n", c, iz_digit(c), c, decapitalize(c));
}

void check_problem3(void) {
    char buffer[80];
    printf("Enter a number: ");
    scanf("%79s", buffer);
    int number = (int) strtol(buffer, nullptr, 10);
    printf("Reference:\t%d %s even\t\t", number, number % 2 == 0 ? "is" : "is not");
    printf("produce_multiple_of_ten(%d) = %d\n", number, produce_multiple_of_ten_reference(number));
    printf("Your code:\t%d %s even\t\t", number, is_even(number) ? "is" : "is not");
    printf("produce_multiple_of_ten(%d) = %d\n", number, produce_multiple_of_ten(number));
}

int main() {
    void (*problem_checkers[NUMBER_OF_PROBLEMS + 1 ])(void) = {
            nullptr,
            check_problem1,
            check_problem2,
            check_problem3
    };
    char buffer[80];
    bool running = true;
    while (running) {
        for (int i = 0; i < NUMBER_OF_PROBLEMS; i++) {
            printf("%d) check problem %d\n", i + 1, i + 1);
        }
        printf("0) Quit\n");
        printf("Select the problem you wish to check: ");
        scanf("%79s", buffer);
        int option = (int) strtol(buffer, nullptr, 10);
        printf("\n");
        if (option < 0 || option > NUMBER_OF_PROBLEMS) {
            printf("Invalid choice %d. Please select a choice between 0 and %d.\n", option, NUMBER_OF_PROBLEMS);
        } else if (option == 0) {
            if (errno == EINVAL) {
                printf("Invalid choice (%s). Please select a number between 0 and %d.\n", buffer, NUMBER_OF_PROBLEMS);
                errno = 0;
            } else {
                printf("Goodbye.\n");
                running = false;
            }
        } else {
            problem_checkers[option]();
        }
        printf("\n");
    }
    return 0;
}