/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file alarm.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Code to manage the piezobuzzer and LEDs.
 *
 ******************************************************************************/

/*
 * ProximityAlarmLab (c) 2023-25 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef ALARM_H
#define ALARM_H

#ifdef __cplusplus
extern "C" {
#endif

#define ALARM_TIMER (2)
#define BUZZER_PIN  (22)

void initialize_alarm(void);
void manage_alarm(void);
void chirp(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //ALARM_H
