/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file proximity-alarm.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for ProximityAlarmLab.
 *
 ******************************************************************************/

/*
 * ProximityAlarmLab (c) 2023-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <CowPi.h>
#include <assert.h>
#include "display.h"
#include "alarm.h"
#include "sensor.h"
#include "sentry.h"

static_assert(ALARM_TIMER != SENSOR_TIMER, "The peripherals need different timer numbers.");
static_assert(BUZZER_PIN != ECHO_PIN, "The peripherals cannot be connected to the same pins.");
static_assert(BUZZER_PIN != TRIGGER_PIN, "The peripherals cannot be connected to the same pins.");

static enum {
    DEMONSTRATE_PIEZOBUZZER, DEMONSTRATE_DISTANCE_SENSOR, PROXIMITY_ALARM
} mode;

void setup(void) {
    cowpi_setup(0,
                (cowpi_display_module_t) {.display_module = NO_MODULE},
                (cowpi_display_module_protocol_t) {.protocol = NO_PROTOCOL}
               );
    initialize_display(16);
    initialize_alarm();
    initialize_sensor();
    draw_logo();
    delay(1000);
    clear_display();
    if (cowpi_right_switch_is_in_left_position()) {
        if (cowpi_left_switch_is_in_left_position()) {
            mode = DEMONSTRATE_PIEZOBUZZER;
            display_string(7, "piezobuzzer");
        } else {
            display_string(7, "ultrasonic");
            mode = DEMONSTRATE_DISTANCE_SENSOR;
        }
    } else {
        display_string(7, "prox alarm");
        mode = PROXIMITY_ALARM;
    }
}

void loop(void) {
    switch (mode) {
        case DEMONSTRATE_PIEZOBUZZER:
            manage_alarm();
            break;
        case DEMONSTRATE_DISTANCE_SENSOR:
            manage_sensor();
            break;
        case PROXIMITY_ALARM:
            detect_intruders();
            break;
        default:
            display_string(0, "****************");
            display_string(1, "Unexpected Mode!");
            display_string(2, "****************");
    }
    count_visits(7);
}
