/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file sentry.h
 *
 * @author Christopher A. Bohn
 *
 * @brief A proximity alarm that continuously checks for nearby objects,
 *      sounding an alert that becomes more urgent when objects are nearer.
 *
 ******************************************************************************/

/*
 * ProximityAlarmLab (c) 2023-25 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef SENTRY_H
#define SENTRY_H

#ifdef __cplusplus
extern "C" {
#endif

void detect_intruders(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //SENTRY_H
