all: lab

lab: keyboardlab.tex ../../common/assignment.tex ../../common/semester.tex ../../common/storylines.tex
	pdflatex keyboardlab
#	bibtex   keyboardlab
	pdflatex keyboardlab
	pdflatex keyboardlab

