/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file remotely-manipulated-arm.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for RotaryMotionLab.
 *
 ******************************************************************************/

/*
 * RotaryMotionLab (c) 2025 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <CowPi.h>
#include "display.h"
#include "io_functions.h"
#include "rotary-encoder.h"
#include "servomotor.h"
#include "timer.h"

static enum {
    DEMONSTRATE_ROTARY_ENCODER, DEMONSTRATE_SERVO, INPUT_TO_ACTUATION
} mode;

void setup(void) {
    cowpi_setup(0,
                (cowpi_display_module_t) {.display_module = NO_MODULE},
                (cowpi_display_module_protocol_t) {.protocol = NO_PROTOCOL}
               );
    initialize_display(16);
    initialize_io();
    initialize_timer();
    center_servo();
    draw_logo();
    delay(1000);
    clear_display();
    if (cowpi_right_switch_is_in_left_position()) {
        if (cowpi_left_switch_is_in_left_position()) {
            display_string(7, "servo");
            mode = DEMONSTRATE_SERVO;
        } else {
            mode = DEMONSTRATE_ROTARY_ENCODER;
            display_string(7, "rotary encoder");
        }
    } else {
        display_string(7, "remote control");
        mode = INPUT_TO_ACTUATION;
    }
}

void loop(void) {
    switch (mode) {
        case DEMONSTRATE_ROTARY_ENCODER:
            count_rotations();
            break;
        case DEMONSTRATE_SERVO:
            test_servo();
            break;
        case INPUT_TO_ACTUATION:
            switch(get_direction()) {
                case CLOCKWISE:
                    servo_step_clockwise();
                    break;
                case COUNTERCLOCKWISE:
                    servo_step_counterclockwise();
                    break;
                default:
                    ;
            }
            break;
        default:
            display_string(0, "****************");
            display_string(1, "Unexpected Mode!");
            display_string(2, "****************");
    }
    count_visits(7);
}
