/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file servomotor.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Function prototypes to direct the behavior of a servomotor.
 *
 ******************************************************************************/

/*
 * RotaryMotionLab (c) 2025 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef SERVOMOTOR_H
#define SERVOMOTOR_H

#define PULSE_INCREMENT_uS      (100)

#define SIGNAL_PERIOD_uS        (20000)
#define MINIMUM_PULSE_WIDTH_uS  (500)
#define MAXIMUM_PULSE_WIDTH_uS  (2500)

void center_servo(void);
void servo_step_clockwise(void);
void servo_step_counterclockwise(void);
void shape_pulse(void);
void test_servo(void);

#endif //SERVOMOTOR_H
