/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file linkedlistlab.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for LinkedListLab.
 *
 ******************************************************************************/

/*
 * LinkedListLab (c) 2021-25 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include "sorted-test.h"
#include "word-entry-test.h"
#include "list-test.h"

#define NUMBER_OF_TESTS (7)

int main(void) {
    void (*problem_checkers[NUMBER_OF_TESTS + 1])(void) = {
            NULL,
            test_word_entry,
            test_list,
            test_alphabetical_functions,
            test_insert_word_empty_list,
            test_insert_word_singleton_list,
            test_insert_word_populated_list,
            test_build_list,
    };
    char *test_names[NUMBER_OF_TESTS + 1] = {
            "Quit",
            "Test word_entry",
            "Test list",
            "Test alphabetical functions",
            "Test insert_word (empty list)",
            "Test insert_word (singleton list)",
            "Test insert_word (populated list)",
            "Create and print book list",
    };
    char buffer[80];
    bool running = true;
    while (running) {
        for (int i = 0; i < NUMBER_OF_TESTS + 1; i++) {
            printf("%d) %s\n", i, test_names[i]);
        }
        printf("Select the task you wish to check: ");
        scanf("%79s", buffer);
        int option = (int) strtol(buffer, NULL, 10);
        printf("\n");
        if (option < 0 || option > NUMBER_OF_TESTS) {
            printf("Invalid choice %d. Please select a choice between 0 and %d.\n", option, NUMBER_OF_TESTS);
        } else if (option == 0) {
            if (errno == EINVAL) {
                printf("Invalid choice (%s). Please select a number between 0 and %d.\n", buffer, NUMBER_OF_TESTS);
                errno = 0;
            } else {
                printf("Goodbye.\n");
                running = false;
            }
        } else {
            char c;
            scanf("%c", &c);        // consume the newline character
            problem_checkers[option]();
        }
        printf("\n");
    }
    return 0;
}
