/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file keyboardlab.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Function prototypes for KeyboardLab.
 *
 ******************************************************************************/

/*
 * KeyboardLab (c) 2021-23 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef KEYBOARDLAB_H
#define KEYBOARDLAB_H

#include <stdlib.h>

char *generate_email(char *destination, size_t destination_size);
char iz_digit(char character);
char decapitalize(char character);
int is_even(int value);
int produce_multiple_of_ten(int seed);

#endif //KEYBOARDLAB_H
