all: ssbc warmup polling interrupts

ssbc: ssbc.tex
	pdflatex ssbc.tex
	pdflatex ssbc.tex
	pdflatex ssbc.tex

warmup: ssbclab-warmup.tex ../../common/assignment.tex
	pdflatex ssbclab-warmup.tex
	pdflatex ssbclab-warmup.tex
	pdflatex ssbclab-warmup.tex

polling: ssbclab-polling.tex ../../common/assignment.tex
	pdflatex ssbclab-polling.tex
	pdflatex ssbclab-polling.tex
	pdflatex ssbclab-polling.tex

interrupts: ssbclab-interrupts.tex ../../common/assignment.tex
	pdflatex ssbclab-interrupts.tex
	pdflatex ssbclab-interrupts.tex
	pdflatex ssbclab-interrupts.tex
